A=[1:8;20:-2:6;2.^(1:8)]
B=sum(A)
C=sum(A,2)
D=reshape(A,6,4)
E=max(A)
F=max(A,[],2)
G=max(A,2) %kicsereli az adott szamra azt ami nem nagyobb nala
H=flipud(A)
I=fliplr(A)
J=size(A)
K=length(A)